version: "3.9"

services:
  postgres:
    image: postgres:16.2
    container_name: shuttertrack_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: shutterdb
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: