# Test profile for ShutterTrackAPI
spring:
  config:
    activate:
      on-profile: test

  # In-memory database (H2) only for tests
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 10000
      max-lifetime: 30000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: create-drop   # таблицы создаются и удаляются каждый запуск тестов
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# File validation (можно оставить дефолтное, чтобы не падали тесты)
file:
  validation:
    max-size: 10485760 # 10 MB
    allowed-types: NEF,CR2,ORF,ARW